version: '3.7'

services:
  app:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

    build: .
    shm_size: '2gb'
    volumes:
      - type: bind
        source: "${SERVICES_ROOT}/subscriber/db"
        target: /db
      - type: bind
        source: "${SERVICES_ROOT}/subscriber/storage"
        target: /storage
      - type: bind
        source: "${SERVICES_ROOT}/subscriber/logs"
        target: /logs
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - "${SERVICES_ROOT}/subscriber/.env"
    environment:
      - STORAGE_PATH=/storage
      - DATABASE_PATH=/db/db.sqlite3
      - LOGS_PATH=/logs
    container_name: subscriber_app
