version: '3.8'

services:
  app:
    build: .
    shm_size: '2gb'
    volumes:
      - type: bind
        source: /dbs/subscriber/
        target: /db
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - /secret/subscriber/.env
