version: '3.7'

services:
  app:
    build: .
    shm_size: '2gb'
    volumes:
      - type: bind
        source: "${SERVICES_ROOT}/subscriber/db"
        target: /db
      - type: bind
        source: "${SERVICES_ROOT}/subscriber/storage"
        target: /storage
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - "${SERVICES_ROOT}/subscriber/.env"
    environment:
      - STORAGE_PATH=/storage
      - DATABASE_PATH=/db/db.sqlite3
    container_name: subscriber_app
