version: '3.7'

services:
  app:
    build: .
    command: ./run-app.sh
    depends_on:
      - db
    volumes:
      - db:/db
      - storage:/storage
      - logs:/logs
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - "${SERVICES_ROOT}/subscriber/.env"
    environment:
      - STORAGE_PATH=/storage
      - LOGS_PATH=/logs
      - REDIS=redis

  # db
  db:
    image: 'postgres:14.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /db/postgres
    volumes:
      - db:/db
    expose:
      - 5432

  #  pgadmin:
  #    container_name: pgadmin_container
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #      PGADMIN_DEFAULT_PASSWORD: admin
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #
  #    volumes:
  #      - /db:/var/lib
  #    ports:
  #      - '127.0.0.1:5050:80'

  # workers
  celery:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M

    build: .
    command: ./run-celery.sh
    shm_size: '2gb'
    depends_on:
      - redis

    volumes:
      - db:/db
      - storage:/storage
      - logs:/logs
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - "${SERVICES_ROOT}/subscriber/.env"
    environment:
      - STORAGE_PATH=/storage
      - DATABASE_PATH=/db/db.sqlite3
      - LOGS_PATH=/logs
      - REDIS=redis

  redis:
    image: 'redis:6.2'
    expose:
      - '6379'
    ports:
      - '10.76.0.1:6379:6379'

volumes:
  static_volume:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${SERVICES_ROOT}/subscriber/db"

  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${SERVICES_ROOT}/subscriber/storage"

  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${SERVICES_ROOT}/subscriber/logs"
