version: "3.9"

services:
  main:
    build:
      dockerfile: services/main/Dockerfile
      context: ..

    volumes:
      - '${VOLUMES_ROOT}/storage:/storage'
      - '${VOLUMES_ROOT}/logs:/logs'
      - '${VOLUMES_ROOT}/db:/db'

    environment:
      STORAGE_PATH: /storage
      LOGS_PATH: /logs
      DB_PATH: /db/db.sqlite3
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}

    command: python main.py
      #    restart: on-failure
